# Generated by Django 5.2.7 on 2025-10-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workforceevent',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='workforceevent',
            old_name='participants',
            new_name='employees',
        ),
        migrations.RenameField(
            model_name='workforceevent',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='workforceevent',
            old_name='all_day',
            new_name='is_all_day',
        ),
        migrations.RenameField(
            model_name='workforceevent',
            old_name='start_datetime',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='workforceevent',
            name='department',
        ),
        migrations.RemoveField(
            model_name='workforceevent',
            name='is_recurring',
        ),
    ]
